[package]
name = "rate-limit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2.3"
once_cell = "1.10.0"
thiserror = "1.0.30"
time = "0.3.9"
